//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oratoria17.serviceOratoria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jury", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class Jury : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJuryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameCriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCriteria {
            get {
                return this.IdCriteriaField;
            }
            set {
                if ((this.IdCriteriaField.Equals(value) != true)) {
                    this.IdCriteriaField = value;
                    this.RaisePropertyChanged("IdCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJury {
            get {
                return this.IdJuryField;
            }
            set {
                if ((this.IdJuryField.Equals(value) != true)) {
                    this.IdJuryField = value;
                    this.RaisePropertyChanged("IdJury");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRound {
            get {
                return this.IdRoundField;
            }
            set {
                if ((this.IdRoundField.Equals(value) != true)) {
                    this.IdRoundField = value;
                    this.RaisePropertyChanged("IdRound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCriteria {
            get {
                return this.NameCriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NameCriteriaField, value) != true)) {
                    this.NameCriteriaField = value;
                    this.RaisePropertyChanged("NameCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoundDescription {
            get {
                return this.RoundDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundDescriptionField, value) != true)) {
                    this.RoundDescriptionField = value;
                    this.RaisePropertyChanged("RoundDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Educational_CenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdStudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Educational_Center {
            get {
                return this.Educational_CenterField;
            }
            set {
                if ((object.ReferenceEquals(this.Educational_CenterField, value) != true)) {
                    this.Educational_CenterField = value;
                    this.RaisePropertyChanged("Educational_Center");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdStudent {
            get {
                return this.IdStudentField;
            }
            set {
                if ((this.IdStudentField.Equals(value) != true)) {
                    this.IdStudentField = value;
                    this.RaisePropertyChanged("IdStudent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Criteria", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class Criteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCriteria {
            get {
                return this.IdCriteriaField;
            }
            set {
                if ((this.IdCriteriaField.Equals(value) != true)) {
                    this.IdCriteriaField = value;
                    this.RaisePropertyChanged("IdCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Element", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class Element : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdElementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCriteria {
            get {
                return this.IdCriteriaField;
            }
            set {
                if ((this.IdCriteriaField.Equals(value) != true)) {
                    this.IdCriteriaField = value;
                    this.RaisePropertyChanged("IdCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdElement {
            get {
                return this.IdElementField;
            }
            set {
                if ((this.IdElementField.Equals(value) != true)) {
                    this.IdElementField = value;
                    this.RaisePropertyChanged("IdElement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoundResults", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class RoundResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Element1ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Element2ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Element3ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Element4ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Oratoria17.serviceOratoria.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalCriteriaValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Element1Value {
            get {
                return this.Element1ValueField;
            }
            set {
                if ((this.Element1ValueField.Equals(value) != true)) {
                    this.Element1ValueField = value;
                    this.RaisePropertyChanged("Element1Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Element2Value {
            get {
                return this.Element2ValueField;
            }
            set {
                if ((this.Element2ValueField.Equals(value) != true)) {
                    this.Element2ValueField = value;
                    this.RaisePropertyChanged("Element2Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Element3Value {
            get {
                return this.Element3ValueField;
            }
            set {
                if ((this.Element3ValueField.Equals(value) != true)) {
                    this.Element3ValueField = value;
                    this.RaisePropertyChanged("Element3Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Element4Value {
            get {
                return this.Element4ValueField;
            }
            set {
                if ((this.Element4ValueField.Equals(value) != true)) {
                    this.Element4ValueField = value;
                    this.RaisePropertyChanged("Element4Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Round {
            get {
                return this.RoundField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundField, value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Oratoria17.serviceOratoria.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCriteriaValue {
            get {
                return this.TotalCriteriaValueField;
            }
            set {
                if ((this.TotalCriteriaValueField.Equals(value) != true)) {
                    this.TotalCriteriaValueField = value;
                    this.RaisePropertyChanged("TotalCriteriaValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalValue {
            get {
                return this.TotalValueField;
            }
            set {
                if ((this.TotalValueField.Equals(value) != true)) {
                    this.TotalValueField = value;
                    this.RaisePropertyChanged("TotalValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalRoundResults", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class GlobalRoundResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Criteria1ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Criteria2ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Criteria3ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDRoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PenalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Oratoria17.serviceOratoria.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Criteria1Value {
            get {
                return this.Criteria1ValueField;
            }
            set {
                if ((this.Criteria1ValueField.Equals(value) != true)) {
                    this.Criteria1ValueField = value;
                    this.RaisePropertyChanged("Criteria1Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Criteria2Value {
            get {
                return this.Criteria2ValueField;
            }
            set {
                if ((this.Criteria2ValueField.Equals(value) != true)) {
                    this.Criteria2ValueField = value;
                    this.RaisePropertyChanged("Criteria2Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Criteria3Value {
            get {
                return this.Criteria3ValueField;
            }
            set {
                if ((this.Criteria3ValueField.Equals(value) != true)) {
                    this.Criteria3ValueField = value;
                    this.RaisePropertyChanged("Criteria3Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRound {
            get {
                return this.IDRoundField;
            }
            set {
                if ((this.IDRoundField.Equals(value) != true)) {
                    this.IDRoundField = value;
                    this.RaisePropertyChanged("IDRound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Penal {
            get {
                return this.PenalField;
            }
            set {
                if ((this.PenalField.Equals(value) != true)) {
                    this.PenalField = value;
                    this.RaisePropertyChanged("Penal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoundDescription {
            get {
                return this.RoundDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundDescriptionField, value) != true)) {
                    this.RoundDescriptionField = value;
                    this.RaisePropertyChanged("RoundDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Oratoria17.serviceOratoria.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinalResults", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class FinalResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Round1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Round1PondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Round2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Round2PondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Round3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Round3PondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Oratoria17.serviceOratoria.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Round1 {
            get {
                return this.Round1Field;
            }
            set {
                if ((this.Round1Field.Equals(value) != true)) {
                    this.Round1Field = value;
                    this.RaisePropertyChanged("Round1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Round1Pond {
            get {
                return this.Round1PondField;
            }
            set {
                if ((this.Round1PondField.Equals(value) != true)) {
                    this.Round1PondField = value;
                    this.RaisePropertyChanged("Round1Pond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Round2 {
            get {
                return this.Round2Field;
            }
            set {
                if ((this.Round2Field.Equals(value) != true)) {
                    this.Round2Field = value;
                    this.RaisePropertyChanged("Round2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Round2Pond {
            get {
                return this.Round2PondField;
            }
            set {
                if ((this.Round2PondField.Equals(value) != true)) {
                    this.Round2PondField = value;
                    this.RaisePropertyChanged("Round2Pond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Round3 {
            get {
                return this.Round3Field;
            }
            set {
                if ((this.Round3Field.Equals(value) != true)) {
                    this.Round3Field = value;
                    this.RaisePropertyChanged("Round3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Round3Pond {
            get {
                return this.Round3PondField;
            }
            set {
                if ((this.Round3PondField.Equals(value) != true)) {
                    this.Round3PondField = value;
                    this.RaisePropertyChanged("Round3Pond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Oratoria17.serviceOratoria.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Round", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOratoria")]
    [System.SerializableAttribute()]
    public partial class Round : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDRoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRound {
            get {
                return this.IDRoundField;
            }
            set {
                if ((this.IDRoundField.Equals(value) != true)) {
                    this.IDRoundField = value;
                    this.RaisePropertyChanged("IDRound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceOratoria.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckStatus", ReplyAction="http://tempuri.org/IService/CheckStatusResponse")]
        bool CheckStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckStatus", ReplyAction="http://tempuri.org/IService/CheckStatusResponse")]
        System.Threading.Tasks.Task<bool> CheckStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetJuryData", ReplyAction="http://tempuri.org/IService/GetJuryDataResponse")]
        Oratoria17.serviceOratoria.Jury[] GetJuryData(string JuryPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetJuryData", ReplyAction="http://tempuri.org/IService/GetJuryDataResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Jury[]> GetJuryDataAsync(string JuryPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveStudents", ReplyAction="http://tempuri.org/IService/GetActiveStudentsResponse")]
        Oratoria17.serviceOratoria.Student[] GetActiveStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveStudents", ReplyAction="http://tempuri.org/IService/GetActiveStudentsResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Student[]> GetActiveStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCriterias", ReplyAction="http://tempuri.org/IService/GetCriteriasResponse")]
        Oratoria17.serviceOratoria.Criteria[] GetCriterias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCriterias", ReplyAction="http://tempuri.org/IService/GetCriteriasResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Criteria[]> GetCriteriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetElements", ReplyAction="http://tempuri.org/IService/GetElementsResponse")]
        Oratoria17.serviceOratoria.Element[] GetElements(int IDCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetElements", ReplyAction="http://tempuri.org/IService/GetElementsResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Element[]> GetElementsAsync(int IDCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetStudentEvaluation", ReplyAction="http://tempuri.org/IService/SetStudentEvaluationResponse")]
        bool SetStudentEvaluation(decimal Element1, decimal Element2, decimal Element3, decimal Element4, int IDStudent, int IDJury, int IDRound);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetStudentEvaluation", ReplyAction="http://tempuri.org/IService/SetStudentEvaluationResponse")]
        System.Threading.Tasks.Task<bool> SetStudentEvaluationAsync(decimal Element1, decimal Element2, decimal Element3, decimal Element4, int IDStudent, int IDJury, int IDRound);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeactivateJury", ReplyAction="http://tempuri.org/IService/DeactivateJuryResponse")]
        bool DeactivateJury(int IDJury);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeactivateJury", ReplyAction="http://tempuri.org/IService/DeactivateJuryResponse")]
        System.Threading.Tasks.Task<bool> DeactivateJuryAsync(int IDJury);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRoundResults", ReplyAction="http://tempuri.org/IService/GetRoundResultsResponse")]
        Oratoria17.serviceOratoria.RoundResults[] GetRoundResults(int IDJury, int IDRound);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRoundResults", ReplyAction="http://tempuri.org/IService/GetRoundResultsResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.RoundResults[]> GetRoundResultsAsync(int IDJury, int IDRound);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGlobalRoundResults", ReplyAction="http://tempuri.org/IService/GetGlobalRoundResultsResponse")]
        Oratoria17.serviceOratoria.GlobalRoundResults[] GetGlobalRoundResults(int IDRound);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGlobalRoundResults", ReplyAction="http://tempuri.org/IService/GetGlobalRoundResultsResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.GlobalRoundResults[]> GetGlobalRoundResultsAsync(int IDRound);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFinalResults", ReplyAction="http://tempuri.org/IService/GetFinalResultsResponse")]
        Oratoria17.serviceOratoria.FinalResults[] GetFinalResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFinalResults", ReplyAction="http://tempuri.org/IService/GetFinalResultsResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.FinalResults[]> GetFinalResultsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRoundDetails", ReplyAction="http://tempuri.org/IService/GetRoundDetailsResponse")]
        Oratoria17.serviceOratoria.Round[] GetRoundDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRoundDetails", ReplyAction="http://tempuri.org/IService/GetRoundDetailsResponse")]
        System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Round[]> GetRoundDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetDevicetoJury", ReplyAction="http://tempuri.org/IService/SetDevicetoJuryResponse")]
        bool SetDevicetoJury(int IDJury, string DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetDevicetoJury", ReplyAction="http://tempuri.org/IService/SetDevicetoJuryResponse")]
        System.Threading.Tasks.Task<bool> SetDevicetoJuryAsync(int IDJury, string DeviceID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Oratoria17.serviceOratoria.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Oratoria17.serviceOratoria.IService>, Oratoria17.serviceOratoria.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckStatus() {
            return base.Channel.CheckStatus();
        }
        
        public System.Threading.Tasks.Task<bool> CheckStatusAsync() {
            return base.Channel.CheckStatusAsync();
        }
        
        public Oratoria17.serviceOratoria.Jury[] GetJuryData(string JuryPass) {
            return base.Channel.GetJuryData(JuryPass);
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Jury[]> GetJuryDataAsync(string JuryPass) {
            return base.Channel.GetJuryDataAsync(JuryPass);
        }
        
        public Oratoria17.serviceOratoria.Student[] GetActiveStudents() {
            return base.Channel.GetActiveStudents();
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Student[]> GetActiveStudentsAsync() {
            return base.Channel.GetActiveStudentsAsync();
        }
        
        public Oratoria17.serviceOratoria.Criteria[] GetCriterias() {
            return base.Channel.GetCriterias();
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Criteria[]> GetCriteriasAsync() {
            return base.Channel.GetCriteriasAsync();
        }
        
        public Oratoria17.serviceOratoria.Element[] GetElements(int IDCriteria) {
            return base.Channel.GetElements(IDCriteria);
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Element[]> GetElementsAsync(int IDCriteria) {
            return base.Channel.GetElementsAsync(IDCriteria);
        }
        
        public bool SetStudentEvaluation(decimal Element1, decimal Element2, decimal Element3, decimal Element4, int IDStudent, int IDJury, int IDRound) {
            return base.Channel.SetStudentEvaluation(Element1, Element2, Element3, Element4, IDStudent, IDJury, IDRound);
        }
        
        public System.Threading.Tasks.Task<bool> SetStudentEvaluationAsync(decimal Element1, decimal Element2, decimal Element3, decimal Element4, int IDStudent, int IDJury, int IDRound) {
            return base.Channel.SetStudentEvaluationAsync(Element1, Element2, Element3, Element4, IDStudent, IDJury, IDRound);
        }
        
        public bool DeactivateJury(int IDJury) {
            return base.Channel.DeactivateJury(IDJury);
        }
        
        public System.Threading.Tasks.Task<bool> DeactivateJuryAsync(int IDJury) {
            return base.Channel.DeactivateJuryAsync(IDJury);
        }
        
        public Oratoria17.serviceOratoria.RoundResults[] GetRoundResults(int IDJury, int IDRound) {
            return base.Channel.GetRoundResults(IDJury, IDRound);
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.RoundResults[]> GetRoundResultsAsync(int IDJury, int IDRound) {
            return base.Channel.GetRoundResultsAsync(IDJury, IDRound);
        }
        
        public Oratoria17.serviceOratoria.GlobalRoundResults[] GetGlobalRoundResults(int IDRound) {
            return base.Channel.GetGlobalRoundResults(IDRound);
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.GlobalRoundResults[]> GetGlobalRoundResultsAsync(int IDRound) {
            return base.Channel.GetGlobalRoundResultsAsync(IDRound);
        }
        
        public Oratoria17.serviceOratoria.FinalResults[] GetFinalResults() {
            return base.Channel.GetFinalResults();
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.FinalResults[]> GetFinalResultsAsync() {
            return base.Channel.GetFinalResultsAsync();
        }
        
        public Oratoria17.serviceOratoria.Round[] GetRoundDetails() {
            return base.Channel.GetRoundDetails();
        }
        
        public System.Threading.Tasks.Task<Oratoria17.serviceOratoria.Round[]> GetRoundDetailsAsync() {
            return base.Channel.GetRoundDetailsAsync();
        }
        
        public bool SetDevicetoJury(int IDJury, string DeviceID) {
            return base.Channel.SetDevicetoJury(IDJury, DeviceID);
        }
        
        public System.Threading.Tasks.Task<bool> SetDevicetoJuryAsync(int IDJury, string DeviceID) {
            return base.Channel.SetDevicetoJuryAsync(IDJury, DeviceID);
        }
    }
}
